### ISSUE TITLE
Playlist not loaded while last playing streamIndex exceeds maxAllowedDynamicStreamIndex

### ISSUE THREAD

**Issue by lifespoiler** [kutu/GrindPlayer#11]
Scenario:
last playing streamIndex for given url was 2. On jsbridge player is set maxAllowedDynamicStreamIndex(1)
Result:
no qualities to switch, player plays the first stream from the playlist...

Is it possible to set something like defaultStreamIndex to play? or turn off loading the sharedObject settings, maybe override them?

btw.great job, love your work!

**Comment by kutu** [comment]
try this version https://dl.dropboxusercontent.com/u/343099/GrindPlayer.swf

**Comment by lifespoiler** [comment]
i'm affraid it won't because i'm using hls plugin (from onlinelib.de) assigned to my domain... so I have to recompile on every change :) 
I think startStreamIndex form flashvars should do the trick, what do you think?

**Comment by kutu** [comment]
it doesnt matter what plugin you use, start index is choosen by my player, not plugin

`src_resourceInitialIndex` should do the trick, but in my player i will use local saved index if exists instead of `src_resourceInitialIndex`

if you want to change it, change the player
