### ISSUE TITLE
1838 ERROR Context-0-ae [class PlayerViewMediator] Media is null

### ISSUE THREAD

**Issue by peixd** [kutu/GrindPlayer#12]
i downloaded the source code and compiled it in flash builder 4.5 successfully. so i debug it in my flash builder, and i got the log as follows:

1352 DEBUG Context-0-ae [object ExtensionInstaller] Installing extension [object InjectableLoggerExtension]
1353 DEBUG Context-0-ae [object ExtensionInstaller] Installing extension [object ContextViewExtension]
1354 DEBUG Context-0-ae [object ExtensionInstaller] Installing extension [object EventDispatcherExtension]
1354 DEBUG Context-0-ae [object ExtensionInstaller] Installing extension [object LocalEventMapExtension]
1355 DEBUG Context-0-ae [object ExtensionInstaller] Installing extension [object ViewManagerExtension]
1356 DEBUG Context-0-ae [object ExtensionInstaller] Installing extension [object StageObserverExtension]
1357 DEBUG Context-0-ae [object ExtensionInstaller] Installing extension [object MediatorMapExtension]
1357 DEBUG Context-0-ae [object ExtensionInstaller] Installing extension [object StageSyncExtension]
1358 DEBUG Context-0-ae [object ConfigManager] Not yet initialized. Queuing config class [class ContextViewListenerConfig]
1359 DEBUG Context-0-ae [object ConfigManager] Not yet initialized. Queuing config object [object AppConfig]
1359 DEBUG Context-0-ae [object ConfigManager] Not yet initialized. Queuing config object [object ContextView]
1359 DEBUG Context-0-ae [object ContextViewExtension] Mapping GrindPlayer as contextView
1361 DEBUG Context-0-ae [object StageSyncExtension] Context view is not yet on stage. Waiting...
1699 DEBUG Context-0-ae [object StageSyncExtension] Context view is now on stage. Initializing context...
1701 INFO Context-0-ae Context-0-ae Initializing...
1714 DEBUG Context-0-ae [object StageObserverExtension] Creating genuine StageObserver Singleton
1715 DEBUG Context-0-ae [object ConfigManager] Now initializing. Instantiating config class [class ContextViewListenerConfig]
1720 DEBUG Context-0-ae [object ConfigManager] Now initializing. Injecting into config object [object AppConfig]
1753 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1757 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1758 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1758 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1759 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1760 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1761 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1761 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1762 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1764 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1765 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1766 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1766 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1767 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1767 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1768 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1769 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1770 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1770 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1771 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1772 DEBUG Context-0-ae [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
1773 DEBUG Context-0-ae [object ConfigManager] Now initializing. Injecting into config object [object ContextView]
1774 INFO Context-0-ae Context-0-ae Initialize complete
1838 ERROR Context-0-ae [class PlayerViewMediator] Media is null
1886 DEBUG Context-0-ae [LayoutRendererBase] ON EXIT FRAME: BEGIN
1887 DEBUG Context-0-ae [LayoutRendererBase] VALIDATING LAYOUT
1887 DEBUG Context-0-ae [LayoutRendererBase] LAYOUT VALIDATED
1888 DEBUG Context-0-ae [LayoutRendererBase] VALIDATING LAYOUT
1888 DEBUG Context-0-ae [LayoutRendererBase] LAYOUT VALIDATED
1889 DEBUG Context-0-ae [LayoutRendererBase] ON EXIT FRAME: END

---

the compiled grindplayer show "initializing" . 
i have uploaded the grindplayer to website and config the crossdomain.xml in the web root .    after that , i open the firefox to browse , i have got no video and the debug info is the same as above. what shall i do ?  

BTW, my html page is as follows:

<script type="text/javascript" src="swfobject.min.js"></script>

```
<script type="text/javascript">
    var flashvars = {
        src: "http://mydomain.com:1200/hls-live/httpwed/352_3C2AA1/liveevent/3C2AA1.m3u8"

    };
    var params = {
        allowFullScreen: true
        , allowScriptAccess: "always"
        , bgcolor: "#000000"
    };
    var attrs = {
        name: "player"
    };

    swfobject.embedSWF("GrindPlayer.swf", "player", "854", "480", "10.2", null, flashvars, params, attrs);
</script>
```

**Comment by kutu** [comment]
grind player doesnt have hls plugin built-in
