### ISSUE TITLE
how to invoke dvr when using Hlsprovider plugin

### ISSUE THREAD

**Issue by deedos** [kutu/GrindPlayer#15]
Hi.
how to invoke dvr in grindplayer when using Hlsprovider plugin ? I could not get the sliding option in the player.

thanks in advance

**Comment by kutu** [comment]
via flashvars `streamType: "dvr"`

**Comment by deedos** [comment]
kutu, i have streamType: "dvr" in here http://player.aovivonaweb.tv/HLSprovider/test/osmf/GrindPlayer.html , but it does not work.
what could I do ?

**Comment by kutu** [comment]
that's mean your plugin override it
