### ISSUE TITLE
Jump to live

### ISSUE THREAD

**Issue by mr-deamon** [kutu/GrindPlayer#17]
Hi Kutu
I have a question regarding an HLS-stream with dvr-functionality. I am able to jump back and forth in time.
Is there a way to jump to the live-position? Is there a switch to display a few pixels on the right end of the timebar as "live"? That would be very helpful!

Chris

**Comment by kutu** [comment]
> Is there a way to jump to the live-position?

click in the most right place in scrubbar

> Is there a switch to display a few pixels on the right end of the timebar as "live"?

no
