### ISSUE TITLE
make: *** [build/GrindPlayer.swf] Error 137

### ISSUE THREAD

**Issue by todostreaming** [kutu/GrindPlayer#2]
Hello, I've tried compiling your code as it is on a Debian 7 64 bits system with Apache Flex SDK 4.10 and Java 1.6 and everything is built:
build
└── libs
    ├── AdvertisementPlugin.swc
    ├── blooddy_crypto.swc
    ├── GrindFramework.swc
    ├── OSMF.swc
    ├── robotlegs-framework-v2.1.0.swc
    └── SubtitlesPlugin.swc
Except GrindPlayer.swf where it exits with Error 137, but no idea where the issue is.

Regards

**Comment by kutu** [comment]
i'm a windows user, maybe other linux users here can help.

**Comment by todostreaming** [comment]
OK, issue solved, it was only changing the the version tag at flex-config.xml
