### ISSUE TITLE
Disable debug

### ISSUE THREAD

**Issue by alexcroox** [kutu/GrindPlayer#21]
My live streaming test with this player works great. However my browser logs are full of debug messages, I can't find anything in the documentation to silence these debug messages?

![screenshot of debug messages](http://cl.ly/XnDi/d)

**Comment by kutu** [comment]
you can now download zip file from [here](http://osmfhls.kutu.ru/docs/grind/), inside two swf files, with and w/o logging

**Comment by alexcroox** [comment]
Thank you very much!
