### ISSUE TITLE
Disable controls entirely

### ISSUE THREAD

**Issue by alexcroox** [kutu/GrindPlayer#22]
I'm trying to ensure the controls never appear as I am live streaming video in a "seamless" window.

My current settings are:

```
autoPlay: true,  
controlBarAutoHide: true,
controlBarAutoHideTimeout: 0,
playButtonOverlay: false
```

However sometimes when I load the page the controls stay visible until I hover over the player, then they will correctly disappear and stay hidden.

How do I ensure they never appear.

**Comment by kutu** [comment]
best solution is get the player and change what you want, but i made little changes to make it work

unfortunately mouse cursor will not hide

**Comment by alexcroox** [comment]
I'm not looking to hide the mouse cursor, just make sure the video controls (play/pause/seek) never appear.
