### ISSUE TITLE
Reconnect to stream after being disconnect

### ISSUE THREAD

**Issue by ghost** [kutu/GrindPlayer#25]
What method do I need to call to reconnect to a stream after the connection is lost? I need to continuously play a live stream.

**Comment by kutu** [comment]
in code, the same as start play some url
via js-api through `player.load()` or `player.setMediaResourceURL(url)`

**Comment by ghost** [comment]
First I need to detect the disconnection event then to play the RTMP stream again. How can I achieve that?

**Comment by kutu** [comment]
try handle "mediaError" event

**Comment by ghost** [comment]
I have added player.play() in MainViewBaseMediator.onMediaError but nothing happened. Do you have a better idea how can I reconnect to the same stream after an error?

**Comment by kutu** [comment]
http://osmfhls.kutu.ru/docs/osmfhls/#handle-error

**Comment by ghost** [comment]
Is this a AS3 or JavaScript? I can't find load method in player class.

**Comment by kutu** [comment]
js api
