### ISSUE TITLE
Setting streamType to "live" does not continue after pausing

### ISSUE THREAD

**Issue by ghost** [kutu/GrindPlayer#26]
When setting streamType flashvar to "live", then click on pause button and after that click on "play" the player does not unpause and video remains paused.

**Comment by kutu** [comment]
if you use rtmp, you can write about it to adobe

**Comment by ghost** [comment]
Hello,

What do you mean by write it to Adobe? I have tested some other players and it behaves normally, the stream continues after unpausing.

**Comment by kutu** [comment]
because this issue in osmf framework, osmf framework developed by adobe
grind player is only interface to osmf framework
