### ISSUE TITLE
how to play with picasaweb?

### ISSUE THREAD

**Issue by dinhkhaihtc** [kutu/GrindPlayer#31]
link picasa https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=e5884ff992d5c8b1&itag=37&source=picasa&cmo=secure_transport=yes&ip=0.0.0.0&ipbits=0&expire=1437487940&sparams=requiressl,id,itag,source,ip,ipbits,expire&signature=9372921D3883FFD246B053DF0878CA1BE75EF01B.3B69B2A41CD2A5F0DF283B6389A3653118B1D9A6&key=lh1

how to play? pls help me?

**Comment by kutu** [comment]
download video, host it on your own server
crossdomain dont allow to playback this video to everyone

**Comment by dinhkhaihtc** [comment]
I do get with google docs , goolge photos , google and youtube drivers

played on jwplayer

demo here: http://cinek.tv/video.php
