### ISSUE TITLE
RTMP QoS Metrics or NetConnection Metrics

### ISSUE THREAD

**Issue by spbell** [kutu/GrindPlayer#32]
Hi,

I am using Grind Player and loving it. I am able to pull qos metrics for HLS/HDS/Progressive downloads, all no problem, however I am unable to get any metrics or data back for RTMP. I was wondering if there was any way given a stream like: rtmp://netrolive.netromedia.com/netrolive/netrolive to access playback bytes, or data received metrics via an the JS API or anything. Your help would greatly be appreciated. 

Cheers

**Comment by kutu** [comment]
can you get this data in SMP player?
cause grind player is mostly based on SMP player

**Comment by spbell** [comment]
This has been resolved on our end, sorry for the inconvience.
