### ISSUE TITLE
The problem

### ISSUE THREAD

**Issue by Lirui072037** [kutu/GrindPlayer#35]
Hi：
      Can you provide this folder（grind）？

```
  import ru.kutu.grind.views.api.IControlBarMenuButtonHide;
```

**Comment by kutu** [comment]
https://github.com/kutu/GrindFramework/blob/master/src/ru/kutu/grind/views/api/IControlBarMenuButtonHide.as

**Comment by Lirui072037** [comment]
Sorry，
   I also need the following file(org.apache.flex.collections.VectorCollection), can you tell me?

   import org.apache.flex.collections.VectorCollection;

**Comment by kutu** [comment]
it should be included in flex framework

**Comment by Lirui072037** [comment]
Oh, thank you

**Comment by Lirui072037** [comment]
I  need the following file(org.apache.flex.collections.VectorCollection)，I'm not here.

![image](https://cloud.githubusercontent.com/assets/13636368/9902762/8053e212-5ca3-11e5-9e14-b957d6a0f736.png)
