### ISSUE TITLE
Manual switch quality with 2 url stream.

### ISSUE THREAD

**Issue by Azef1** [kutu/GrindPlayer#36]
Hi,

I like GrindPlayer but i would like a manual switch between a high quality stream and low quality.
My high quality stream it's: rtmp://@IP/hd_stream
My low quality stream it's: rtmp://@IP/sd_strem

Currently, i have only set one stream with src param but how to put 2 stream ?

Thx

**Comment by kutu** [comment]
create two html buttons and use js-api
http://osmfhls.kutu.ru/docs/grind/#js-api
`player.setMediaResourceURL()`
