### ISSUE TITLE
Player stuck at initializing

### ISSUE THREAD

**Issue by cool-acid** [kutu/GrindPlayer#4]
Player only shows "initializing". I have tried to get it working using both the compiled file from the documentation site and building my own player with the code. I've used the embed code shown in the documentation. It doesn't matter which src I am specifying. It doesn't show any errors in the JS console either. Am I doing something wrong?

**Comment by kutu** [comment]
i can't say anything without the link to the page, where you test it

**Comment by cool-acid** [comment]
Apparently my error was to load the html file directly and not through my local server. Now it's working all right.
I guess this is a bug, and although it's not really relevant, maybe you should warn about this in the readme. 
Thank you!

**Comment by kutu** [comment]
no, this is a flash security policy

**Comment by notanewbie** [comment]
I have this issue too. This is my code (same as on the site):

<html>
<head>
    <title>Grind Player</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="text/javascript" src="http://yandex.st/swfobject/2.2/swfobject.min.js"></script>
    <script type="text/javascript">
        var flashvars = {
            src: "http://hlsdpi-cdn-as4.totalstream.net/dpilive/vidilliontv/vtv/ntrnaturevision/playlist.m3u8"
        };
        var params = {
            allowFullScreen: true
            , allowScriptAccess: "always"
            , bgcolor: "#000000"
        };
        var attrs = {
            name: "player"
        };

        swfobject.embedSWF("GrindPlayer.swf", "player", "854", "480", "10.2", null, flashvars, params, attrs);
    </script>
</head>
<body>
    <div id="player"></div>
</body>
</html>

**Comment by notanewbie** [comment]
P.S. Also does not work with this code:
`<object width="400" height="400" data="GrindPlayer.swf"></object>`
