### ISSUE TITLE
How to change quality list name,the m3u8 file have name tag

### ISSUE THREAD

**Issue by WeBBLiu** [kutu/GrindPlayer#45]
Hi Kutu,

How to change quality list name,the m3u8 file have name tag.

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=500000,RESOLUTION=640x360,NAME="360p SD"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=800000,RESOLUTION=853x480,NAME="480p SD"

I do like quality switch list to show NAME(360p SD, 480p SD) content. can I custom text?

Thank You.
<img src="http://w2.goodtv.tv/images/20170309grindplayer.png" style="max-width:100%;">

**Comment by kutu** [comment]
by changing source code
