### ISSUE TITLE
Can't work live streams... 

### ISSUE THREAD

**Issue by TheAntinormal** [kutu/GrindPlayer#47]
Hello,

I'm sorry to disturb you but I can't make it work.. 

I used the basic example described on the site that is : "http://osmfhls.kutu.ru/docs/grind/"

But I couldn't make it work, with files on my desktop, with http, rtmp ... how should I do ? can someone be kind and help me please ? thanks !

It always keep "initializing"...

Example : https://www.useloom.com/share/d8c1c917aefa402da0edc8dabc794fab

**Comment by kutu** [comment]
its not gonna work
you cant playback ts files without m3u8 playlist and my osmfhls plugin
and you need to test it on local server at least, you cant just open html file in browser and expect it to work, because of security policy in flashplayer
