### ISSUE TITLE
Player & Add event listeners

### ISSUE THREAD

**Issue by kvervo** [kutu/GrindPlayer#6]
Hi!

I am following the documentation (http://osmfhls.kutu.ru/docs/grind/) and trying work with add event listeners.

On my local version AddEventListeners are not working.

I am trying the following code from the js console in Chrome after loading the player: 
var p = document.getElementById("player");
p.addEventListener("loadStateChange", function(){ alert("LoadState") });

Tried to add event listeners for: loadStateChange, playStateChange , volumeChange, mutedChange, mediaError. None of this events seem to fire.

**Comment by kutu** [comment]
`addEventListener(eventName:String, callbackFunctionName:String)`

```
p.addEventListener("loadStateChange", "myFunction");
function myFunction(){ alert("LoadState") }
```
