### ISSUE TITLE
 Stream not found

### ISSUE THREAD

**Issue by xudongwang** [kutu/GrindPlayer#8]
var flashvars = {
            src: "http://osmfhls.kutu.ru/static/vod/sl_vod.m3u8",
             javascriptCallbackFunction: "onJSBridge"
        };
        var params = {
            allowFullScreen: true
            , allowScriptAccess: "always"
            , bgcolor: "#000000"
        };
        var attrs = {
            name: "player"
        };

```
    swfobject.embedSWF("./Content/GrindPlayer.swf", "player", "854", "480", "10.3", null, flashvars, params, attrs);

    var player;
    function onJSBridge(playerId, event, data) {
        switch (event) {
            case "onJavaScriptBridgeCreated":
                // reference to player
                player = document.getElementById(playerId);
                player.addEventListener("mediaError", "onMediaError");
                break;

                // player state change
            case "ready":
            case "loading":
            case "playing":
            case "paused":
            case "buffering":

                // other events
            case "mediaSize":
            case "seeking":
            case "seeked":
            case "volumeChange":
            case "durationChange":
            case "timeChange":
            case "progress": // for progressive download only
            case "complete":
            case "advertisement":

            default:
                // console.log(event, data);
                break;
        }
    }

    function onMediaError() {
        //console.log(arguments.callee.name, arguments);
        //alert(arguments);
    }
</script>
```

</head>
<body>
    <div id="player"></div>
</body>

Always returns Message: Stream not found
I don't know why
Please provide help

**Comment by kutu** [comment]
because my site doesnt have crossdomain file, and your server doesnt have access to this stream

**Comment by xudongwang** [comment]
but i see this site(http://osmfhls.kutu.ru/) can access to file.

**Comment by kutu** [comment]
because player hosted here

try to read how crossdomain security policy works in flashplayer

**Comment by xudongwang** [comment]
you means crossdomain m3u8?

**Comment by kutu** [comment]
crossdomain.xml

**Comment by xudongwang** [comment]
ok,thank you very much,I try, if not, ask you again.

(i'm from china)
