### ISSUE TITLE
Stream stops when change tab

### ISSUE THREAD

**Issue by javiercornejo** [kutu/GrindPlayer#9]
Hi everyone!
Player stops playing the stream when change the tab... Is like Chrome set low priority to the player when the tab doesn't have focus. Apparently, player stops downloading packets... is this some setting?

Hope you can help me!

**Comment by kutu** [comment]
> is this some setting?

no, try to use native flashplayer, instead pepperflash

**Comment by javiercornejo** [comment]
Sorry. We updated Player and HLS Plugin and problems solved.
Thanks.
